// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odyasgiwqghuhbjqbznj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9keWFzZ2l3cWdodWhianFiem5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjQ3NDIsImV4cCI6MjA3MzQwMDc0Mn0.Spoy0ZFJTdQzouAwIZnAkRmzUkxFVvCkaU4vECYHyWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});